# spring.application.name=todo

server:
  port: 8282

spring:
  application:
    name: hi_project
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    database: mysql

# swagger setting
springdoc:
  swagger-ui:
    path: /hiapi.html
